---
apiVersion: v1
kind: Namespace
metadata:
  name: ai
---
# PV & PVCs for helicone storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: helicone-data-postgresql-pv
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.100.115
    path: /data2/docker/helicone_data/postgresql
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helicone-data-postgresql-pvc
  namespace: ai
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  volumeName: helicone-data-postgresql-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: helicone-data-clickhouse-pv
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.100.115
    path: /data2/docker/helicone_data/clickhouse
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helicone-data-clickhouse-pvc
  namespace: ai
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  volumeName: helicone-data-clickhouse-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: helicone-data-minio-pv
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.100.115
    path: /data2/docker/helicone_data/minio
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helicone-data-minio-pvc
  namespace: ai
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  volumeName: helicone-data-minio-pv
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helicone
  namespace: ai
  labels:
    app: helicone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helicone
  template:
    metadata:
      labels:
        app: helicone
    spec:
      nodeSelector:
        nvidia.com/gpu: "true"
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      runtimeClassName: nvidia
      containers:
        - name: helicone
          image: registry.home:5000/helicone-test:latest
          ports:
            - containerPort: 22
            - containerPort: 3000 
            - containerPort: 8585 
            - containerPort: 8785 
            - containerPort: 8786 
            - containerPort: 8787 
            - containerPort: 5432 
            - containerPort: 8123 
            - containerPort: 9000 
            - containerPort: 9001 
            - containerPort: 9080 
            - containerPort: 9229 
            - containerPort: 666
          env:
            - name: NEXT_PUBLIC_IS_ON_PREM
              value: "true"
            - name: NEXT_PUBLIC_BETTER_AUTH
              value: "true"
            - name: NEXT_PUBLIC_BASE_PATH
              value: "http://192.168.100.86:3100"
            - name: NEXT_PUBLIC_HELICONE_JAWN_SERVICE
              value: "http://192.168.100.86:8585"
            - name: DATABASE_URL
              value: "postgresql://postgres:password@localhost:5432/helicone_test"
            - name: S3_ENDPOINT
              value: "http://localhost:9080"
            - name: S3_ENDPOINT_PUBLIC
              value: "http://192.168.100.86:9080"
            - name: S3_BUCKET_NAME
              value: "request-response-storage"
            - name: S3_ACCESS_KEY
              value: "minioadmin"
            - name: S3_SECRET_KEY
              value: "minioadmin"
            - name: SMTP_HOST
              value: "192.168.100.174"
            - name: SMTP_PORT
              value: "1025"
            - name: SMTP_SECURE
              value: "false"
            - name: SMTP_USER
              value: "blah"
            - name: SMTP_PASS
              value: "blah"
            - name: BETTER_AUTH_SECRET
              value: "MKUcaeqyMD7UBkGeFYY5hwxKS1aB6Vsi"
            - name: JWT_SECRET
              value: "Ah6j2uYPLr4bN9cXpZq7Wt5vM1KsB8Qw"
            - name: VALHALLA_URL
              value: "http://localhost:8585"
            - name: CLICKHOUSE_CREDS
              value: '{"CLICKHOUSE_HOST":"http://localhost:8123","CLICKHOUSE_USER":"default","CLICKHOUSE_PASSWORD":"","CLICKHOUSE_HQL_USER":"hql_user","CLICKHOUSE_HQL_PASSWORD":""}'
            - name: VERCEL_ENV
              value: "development"

          volumeMounts:
            - name: helicone-data-postgresql
              mountPath: /var/lib/postgresql/17/main
            - name: helicone-data-clickhouse
              mountPath: /var/lib/clickhouse
            - name: helicone-data-minio
              mountPath: /data

      volumes:
        - name: helicone-data-postgresql
          persistentVolumeClaim:
            claimName: helicone-data-postgresql-pvc
        - name: helicone-data-clickhouse
          persistentVolumeClaim:
            claimName: helicone-data-clickhouse-pvc
        - name: helicone-data-minio
          persistentVolumeClaim:
            claimName: helicone-data-minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: helicone-lbsvc
  namespace: ai
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.100.86"
    metallb.universe.tf/allow-shared-ip: "tv-stack"
spec:
  type: LoadBalancer
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app: helicone
  ports:
    - name: sshd
      port: 22
      targetPort: 22
    - name: webapp
      port: 3100
      targetPort: 3000
    - name: jawn
      port: 8585
      targetPort: 8585 
    - name: worker-proxy2
      port: 8785
      targetPort: 8785 
    - name: worker-proxy1
      port: 8786
      targetPort: 8786 
    - name: worker
      port: 8787
      targetPort: 8787 
    - name: postgresql
      port: 5432
      targetPort: 5432
    - name: clickhouse1
      port: 8123
      targetPort: 8123
    - name: clickhouse2
      port: 9000
      targetPort : 9000
    - name: s3-storage-ui
      port: 9001
      targetPort : 9001
    - name: s3-storage
      port: 9080
      targetPort : 9080
    - name: node-debug
      port: 9229
      targetPort : 9229
    - name: http6
      port: 666
      targetPort: 666


